// DOCX export — produces an ATS-safe Word document.
//
// What "ATS-safe" means here:
//   • Single column (no text frames or multi-column layouts).
//   • No tables for layout — ATS parsers (Workday, Greenhouse, iCIMS,
//     Taleo) regularly misread or skip table content. Section headers
//     are headings, not table rows.
//   • Body text is Arial 11pt. Section headers are Arial 11pt bold,
//     UPPERCASE. The exact font choice is also one of the most ATS-
//     compatible choices available.
//   • Bullets are native Word list paragraphs, not unicode "•" characters
//     inside a paragraph — the parser recognizes the list bullet and
//     keeps the content rather than treating it as inline text.
//   • Contact line is the first paragraph, plain text, comma-separated,
//     so a parser that scans top-of-document picks up every channel.
//   • Margins are 0.75" on all sides — the de-facto resume standard.
//
// Determinism: no Date.now() in the document body. Filenames include a
// timestamp from the caller (the UI), not from this module.

import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  LevelFormat,
  Packer,
  PageOrientation,
  Paragraph,
  TextRun,
} from 'docx'
import FileSaver from 'file-saver'
import type { ExperienceEntry, Resume } from '../types'

// ──────────────────────────────────────────────────────────────────────────
// Style constants — change here, document follows.
// ──────────────────────────────────────────────────────────────────────────

const BODY_FONT = 'Arial'
const BODY_SIZE = 22 // DOCX units are half-points: 22 = 11pt
const HEADER_SIZE = 22 // same size, bold + uppercase
const NAME_SIZE = 32 // 16pt
const LINE_SPACING = 1.15

const MARGIN_IN_TWIPS = (inches: number) => Math.round(inches * 1440)

// ──────────────────────────────────────────────────────────────────────────
// Public entry
// ──────────────────────────────────────────────────────────────────────────

/**
 * Build a DOCX blob from a parsed + optimized resume.
 * Returns a Blob so the caller can trigger a save.
 */
export async function buildDocx(resume: Resume): Promise<Blob> {
  const doc = new Document({
    creator: 'Fairshot',
    title: resume.contact.name
      ? `${resume.contact.name} – Resume`
      : 'Resume',
    description: 'Generated by Fairshot',
    styles: {
      default: {
        document: {
          run: { font: BODY_FONT, size: BODY_SIZE },
          paragraph: { spacing: { line: Math.round(LINE_SPACING * 240) } },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: MARGIN_IN_TWIPS(0.75),
              right: MARGIN_IN_TWIPS(0.75),
              bottom: MARGIN_IN_TWIPS(0.75),
              left: MARGIN_IN_TWIPS(0.75),
              header: MARGIN_IN_TWIPS(0.4),
              footer: MARGIN_IN_TWIPS(0.4),
              gutter: 0,
            },
            size: { orientation: PageOrientation.PORTRAIT },
          },
        },
        children: [
          ...buildHeader(resume),
          ...(resume.summary ? buildSummary(resume.summary) : []),
          ...buildExperience(resume.experience),
          ...buildEducation(resume.education),
          ...buildSkills(resume.skills),
          ...(resume.extras.length ? buildExtras(resume.extras) : []),
        ],
      },
    ],
    numbering: {
      config: [
        {
          reference: 'ats-bullets',
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: '\u2022',
              alignment: AlignmentType.LEFT,
              style: {
                run: { font: BODY_FONT, size: BODY_SIZE },
                paragraph: {
                  indent: { left: 360, hanging: 220 },
                  spacing: { line: Math.round(LINE_SPACING * 240), after: 60 },
                },
              },
            },
          ],
        },
      ],
    },
  })

  return await Packer.toBlob(doc)
}

/** Convenience: build and immediately trigger a download. */
export async function downloadDocx(resume: Resume, filename?: string): Promise<void> {
  const blob = await buildDocx(resume)
  FileSaver.saveAs(blob, filename ?? defaultFilename(resume, 'docx'))
}

export function defaultFilename(resume: Resume, ext: string): string {
  const slug = resume.contact.name
    ?.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'resume'
  return `${slug}.${ext}`
}

// ──────────────────────────────────────────────────────────────────────────
// Section builders
// ──────────────────────────────────────────────────────────────────────────

function buildHeader(resume: Resume): Paragraph[] {
  const out: Paragraph[] = []
  const c = resume.contact
  if (c.name) {
    out.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 60 },
        children: [
          new TextRun({
            text: c.name,
            bold: true,
            font: BODY_FONT,
            size: NAME_SIZE,
          }),
        ],
      }),
    )
  }

  const contactBits = [
    c.location,
    c.phone,
    c.email,
    c.linkedin,
    c.portfolio,
  ].filter(Boolean) as string[]

  if (contactBits.length) {
    out.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 120 },
        children: [
          new TextRun({
            text: contactBits.join('  ·  '),
            font: BODY_FONT,
            size: BODY_SIZE,
          }),
        ],
      }),
    )
  }

  return out
}

function buildSummary(summary: string): Paragraph[] {
  return [
    sectionHeader('Summary'),
    new Paragraph({
      children: [new TextRun({ text: summary, font: BODY_FONT, size: BODY_SIZE })],
      spacing: { after: 120 },
    }),
  ]
}

function buildExperience(entries: ExperienceEntry[]): Paragraph[] {
  if (!entries.length) return []
  const out: Paragraph[] = [sectionHeader('Experience')]
  for (const e of entries) {
    // Title + Company + Date on two lines, like every readable resume.
    const titleLine = [e.title, e.company].filter(Boolean).join(' — ')
    out.push(
      new Paragraph({
        spacing: { before: 80, after: 20 },
        tabStops: [{ type: 'right', position: MARGIN_IN_TWIPS(6.5) }],
        children: [
          new TextRun({ text: titleLine, bold: true, font: BODY_FONT, size: BODY_SIZE }),
          ...(e.dateRange
            ? [
                new TextRun({
                  children: ['\t', e.dateRange],
                  bold: false,
                  font: BODY_FONT,
                  size: BODY_SIZE,
                }),
              ]
            : []),
        ],
      }),
    )
    if (e.location) {
      out.push(
        new Paragraph({
          spacing: { after: 20 },
          children: [
            new TextRun({ text: e.location, italics: true, font: BODY_FONT, size: BODY_SIZE }),
          ],
        }),
      )
    }
    for (const bullet of e.bullets) {
      if (!bullet.trim()) continue
      out.push(
        new Paragraph({
          numbering: { reference: 'ats-bullets', level: 0 },
          children: [
            new TextRun({ text: bullet, font: BODY_FONT, size: BODY_SIZE }),
          ],
        }),
      )
    }
  }
  return out
}

function buildEducation(entries: Resume['education']): Paragraph[] {
  if (!entries.length) return []
  const out: Paragraph[] = [sectionHeader('Education')]
  for (const e of entries) {
    const headline = [e.degree, e.field].filter(Boolean).join(', ')
    out.push(
      new Paragraph({
        spacing: { before: 60, after: 20 },
        tabStops: [{ type: 'right', position: MARGIN_IN_TWIPS(6.5) }],
        children: [
          new TextRun({
            text: headline ? `${headline} — ${e.school}` : e.school,
            bold: true,
            font: BODY_FONT,
            size: BODY_SIZE,
          }),
          ...(e.dateRange
            ? [new TextRun({ children: ['\t', e.dateRange], font: BODY_FONT, size: BODY_SIZE })]
            : []),
        ],
      }),
    )
  }
  return out
}

function buildSkills(skills: Resume['skills']): Paragraph[] {
  if (!skills.length) return []
  return [
    sectionHeader('Skills'),
    new Paragraph({
      spacing: { after: 120 },
      children: [
        new TextRun({ text: skills.join(', '), font: BODY_FONT, size: BODY_SIZE }),
      ],
    }),
  ]
}

function buildExtras(extras: Resume['extras']): Paragraph[] {
  return [
    sectionHeader('Additional'),
    ...extras.map(
      (line) =>
        new Paragraph({
          spacing: { after: 60 },
          children: [new TextRun({ text: line, font: BODY_FONT, size: BODY_SIZE })],
        }),
    ),
  ]
}

function sectionHeader(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 160, after: 60 },
    border: {
      bottom: { color: '999999', space: 1, style: BorderStyle.SINGLE, size: 4 },
    },
    children: [
      new TextRun({
        text: text.toUpperCase(),
        bold: true,
        font: BODY_FONT,
        size: HEADER_SIZE,
      }),
    ],
  })
}
